language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ItayZerah/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ItayZerah/docker-react npm run test